[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "chess_seq"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.9"

[tool.setuptools]
packages = ["chess_seq"]